'use strict';

export default Object.freeze({
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  PROFILE_GET_SUCCESS: 'PROFILE_GET_SUCCESS',
  PROFILE_GET_FAILED: 'PROFILE_GET_FAILED',
  PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_IMAGE_UPLOAD_FAILED: 'PROFILE_IMAGE_UPLOAD_FAILED',
  PROFILE_ARRAY_UPDATE_SUCCESS: 'PROFILE_ARRAY_UPDATE_SUCCESS',
});
