'use strict';

export default Object.freeze({
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  PROFILE_GET_SUCCESS: 'PROFILE_GET_SUCCESS',
  PROFILE_GET_FAILED: 'PROFILE_GET_FAILED',
});
